language: go
go:
- "1.14"
before_script: if ! [[ $TRAVIS_TAG ]]; then export LAST_TAG=$(git tag --list | tail -1); export VERSION=$LAST_TAG-$(git rev-list $LAST_TAG..HEAD --count); else export VERSION=$TRAVIS_TAG; fi
script:
- bash ./scripts/package.sh
- go test -v ./...
- go build -ldflags "-X github.com/cloudkarafka/cloudkarafka-manager/config.GitCommit=$TRAVIS_COMMIT
  -X github.com/cloudkarafka/cloudkarafka-manager/config.Version=$VERSION" -tags static -a
  -o cloudkarafka-mgmt.linux
after_success:
- cp cloudkarafka-mgmt.linux target/
- tar -czf cloudkarafka-mgmt.tar.gz target
addons:
  artifacts:
    paths:
    - cloudkarafka-mgmt.tar.gz
    target_paths:
    - "/cloudkarafka-mgmt/$TRAVIS_BRANCH"
deploy:
  - provider: releases
    api_key:
      secure: Runhv5Jnbd+0pyRQCDYwEaRZ51ZlcJNyJ5C9TBeoMREWucNOS4BenbfyJ1aM1gA2MmwbcNUF1sJYWzq4/MKkCB2jrEdpVWIye6VtHWshINpFwSD5wZXYpx8XZ1gQDGUjbf5MFlnPiqLk4wT0r28JTzJzbxl0gsN7T84dBwe2bX7nSHda4856f82iKWE6H8fwk+em/Ev7UKTz12ekQSe98fu0WrJZpvq4PIcjOl/I2lAVPXe3TZfUKqSnluS/N3mxMFJ6pM5Zb/AErXwnjrLh/GeL6NvcHtzaK5/pA8+c4EVvhPRzp3dZkgDthZG1JABJjirUkWJR3saR2IwmLJVSub9tGrxDT2G9uAzqn/Nf4eC/DqlWtMsciS3qOj36d4InzCpwKyfwN9BYxXth6kfw0IsVZt9oK0aNwhWQBh5BgHrWUGeWqAJDoORfNKxN7WwQJnRs3If4tsVp0c/DiY65JzByfOGYwPVZx2FmfUBwtsOvORXKtl3uOZxkCEROQ+FrWVXyewGYQaOSGGB608X2hCwSemLa+IKnZ6YAVQzBkoWEWJzjWEbT5yhxnTwgNah1fnRXMR5VuSBw8qfjEwkhFOFC1FLj0wUPXaflCt9+PPqCvm7KCnpvnO3TIgoO1xUvjUMc0fFdZ2Yy5RxmcplOKVJ2Bt94QJQTJcf7KkQQ8FM=
    file: cloudkarafka-mgmt.tar.gz
    skip_cleanup: true
    on:
      tags: true
notifications:
  slack:
    secure: ktQ1ONer4EBdsZ8Xs3DYAUFWcy/Odxd1+lob8c/aHQMpcqL2XGg28cXiLJGyaUbmOAWGr6BeySRyBBoTyj3fozCB9uy82uwW8Pt4arl7WdQOqvLPvcJLPWe1YOHqGT1j4KAVZKGfY78h66VjKZw7L7ybbntgCPKxgmHz9jtCr4m6yD2Hdrc+1y8xcJRelNPgHSuXul1fCiEbjyw6hpRHg0t6AGbYYREJSygBsyDeXKict/p9CKxS0zBw8NILAOuCwm1G2bIVKm9VnE6GQMNsc2tjYJxy9CdeDwun3zsUNH8NEGLM4Rs1mYqzbC+N9UuuV6zWUOKy8eUYZlGyHqB2Nx3y5FrPMajkJuJO/N4lmX5RhL8o6hTFvv4p7e39+FXS8NCoyRkFjAPBQq0EVscolTNU83FP+bbXQ6/rK5b26Tx3SWLNhhx4mCiH10TXI+jwh/VS1T34MKuG5HVxpOGynLvH5BvZKyFyOalZuiekgHa8CwqrTFhRDb3LpZhcTZ8h0aAbp9IeS0uWJifpo6xLW1ieQUUeQ88Z3+SFhE4gYgpkzRWhFNkvZVRyD/hnZWRG5+fuDD1ImX6ewVkMP8LI/hBr+0L6w5aFCr8m7cc7pmRZEdeJDtqt4Kr+tGq4e50LwndX2B4/t/NV4lq/qY0Jqkx54t0411L7Cmx5fcz3sjs=
