[[constraint]]
  name = "github.com/samuel/go-zookeeper"
  branch = "master"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "1.0.0"

[[constraint]]
  name = "goji.io"
  version = "v2.0"

[[constraint]]
  name = "go.etcd.io/bbolt"
  version = "v1.3.1-etcd.8"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"
